{"name": "Проверка ответа при создании заказа запросом с невалидным хэшем ингредиента аутентифицированным юзером", "status": "failed", "statusDetails": {"message": "AssertionError: assert (400 == 500)\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x00000130061DC3B0>\ncreate_new_user_and_delete = ({'email': 'jasonpark@yahoo.com', 'name': 'Евсей', 'password': '&p0)Rp%!i#'}, {'accessToken': 'Bearer eyJhbGciOiJIUzI1...926ced71803d93c777465287c330784766737938', 'success': True, 'user': {'email': 'jasonpark@yahoo.com', 'name': 'Евсей'}})\n\n    @allure.title('Проверка ответа при создании заказа запросом с невалидным хэшем ингредиента '\n                  'аутентифицированным юзером')\n    @allure.description('В запрос передается хэш несуществующего ингредиента. Аккаунт для проверки создается фикстурой '\n                        'перед тестом и удаляется после.')\n    def test_create_order_invalid_ingredients_authenticated_user_expected_error(self, create_new_user_and_delete):\n        headers = {'Authorization': create_new_user_and_delete[1]['accessToken']}\n        payload = {'ingredients': [IngredientData.invalid_hash_ingredient]}\n        response = requests.post(Urls.order_create, data=payload, headers=headers)\n>       assert response.status_code == 500 and response.json() == {\"success\": False,\n                                                                   \"message\": \"One or more ids provided are incorrect\"}\nE       assert (400 == 500)\nE        +  where 400 = <Response [400]>.status_code\n\ntests\\test_create_order.py:56: AssertionError"}, "description": "В запрос передается хэш несуществующего ингредиента. Аккаунт для проверки создается фикстурой перед тестом и удаляется после.", "start": 1719119535387, "stop": 1719119535611, "uuid": "8aa92f4f-fef4-467e-b0ce-417845b10e3d", "historyId": "c78dc2f65c70f2d33e631820a2d7f09a", "testCaseId": "c78dc2f65c70f2d33e631820a2d7f09a", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_invalid_ingredients_authenticated_user_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "LAPTOP-0911SMBB"}, {"name": "thread", "value": "16156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}