{"name": "Проверка ответа при создании заказа запросом с невалидным хэшем ингредиента аутентифицированным юзером", "status": "failed", "statusDetails": {"message": "AssertionError: assert (400 == 500)\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x000001C7D41DCE30>\ncreate_new_user_and_delete = ({'email': 'apriljensen@gmail.com', 'name': 'Аркадий', 'password': 'W@bf7Kw^2t'}, {'accessToken': 'Bearer eyJhbGciOiJI...32f92a48bd4ffd4ec0e4ea6a6e17f2f838c2', 'success': True, 'user': {'email': 'apriljensen@gmail.com', 'name': 'Аркадий'}})\n\n    @allure.title('Проверка ответа при создании заказа запросом с невалидным хэшем ингредиента '\n                  'аутентифицированным юзером')\n    @allure.description('В запрос передается хэш несуществующего ингредиента. Аккаунт для проверки создается фикстурой '\n                        'перед тестом и удаляется после.')\n    def test_create_order_invalid_ingredients_authenticated_user_expected_error(self, create_new_user_and_delete):\n        headers = {'Authorization': create_new_user_and_delete[1]['accessToken']}\n        payload = {'ingredients': [IngredientData.invalid_hash_ingredient]}\n        response = requests.post(Urls.order_create, data=payload, headers=headers)\n>       assert response.status_code == 500 and response.json() == {\"success\": False,\n                                                                   \"message\": \"One or more ids provided are incorrect\"}\nE       assert (400 == 500)\nE        +  where 400 = <Response [400]>.status_code\n\ntests\\test_create_order.py:57: AssertionError"}, "description": "В запрос передается хэш несуществующего ингредиента. Аккаунт для проверки создается фикстурой перед тестом и удаляется после.", "start": 1718506683011, "stop": 1718506683111, "uuid": "c555a07e-e3c3-42a6-9bc3-fb3427f43f4c", "historyId": "c78dc2f65c70f2d33e631820a2d7f09a", "testCaseId": "c78dc2f65c70f2d33e631820a2d7f09a", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_invalid_ingredients_authenticated_user_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "LAPTOP-0911SMBB"}, {"name": "thread", "value": "3752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}