{"name": "Проверка ответа на запрос изменения данных неаутентифицированного пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert (400 == 401)\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_user_update.TestUserUpdate object at 0x00000242D61E2240>\n\n    @allure.title('Проверка ответа на запрос изменения данных неаутентифицированного пользователя')\n    def test_update_user_unauthenticated_expected_error(self):\n        response = requests.patch(Urls.user_update, headers=Urls.headers, data=TestUserUpdate.updated_user_data)\n>       assert response.status_code == 401 and response.json() == {'success': False,\n                                                                   'message': 'You should be authorised'}\nE       assert (400 == 401)\nE        +  where 400 = <Response [400]>.status_code\n\ntests\\test_user_update.py:24: AssertionError"}, "start": 1719121823730, "stop": 1719121823826, "uuid": "573f48c3-ab8e-446d-96cc-a4fa0533131f", "historyId": "15ddd7987c2e5999e579e59a038213af", "testCaseId": "15ddd7987c2e5999e579e59a038213af", "fullName": "tests.test_user_update.TestUserUpdate#test_update_user_unauthenticated_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "LAPTOP-0911SMBB"}, {"name": "thread", "value": "32628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}